FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the required files to the container
COPY requirements.txt ./
COPY src/process_staging.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


