vars:
  - params.yaml

stages:
  process_staging:
    cmd: python src/process_staging.py
    deps:
      - .env
      - src/process_staging.py
      - params.yaml
    outs:
      - tmp/staging_data:  # temporary staging output, not persisted remotely
          cache: false
          persist: true
  process_curated:
    cmd: python src/process_curated.py
    deps:
      - .env
      - src/process_curated.py
      - tmp/staging_data
      - params.yaml
